stages:
  - build

build:
  stage: build
  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build
    # - cp -r dist/* c:/sangon/project/mes/dist
    - cp -r dist/* c:/other
  environment:
    name: mes
  only:
    - mengyucheng
