const projectModel = {
  namespace: 'project',
  state: {
    projectManage: [
      {
        id: 1,
        code: 111111,
        name: '木木1',
        describe: '描述1',
        creatorName: '大大创建1',
        creatorTime: '2019/10/20',
        changerName: '大大修改1',
        changerTime: '2019/10/20',
        status: 1,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目1',
        copyRight: '1.1',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
        list: [
          {
            id: 3,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 1,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
          {
            id: 4,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 2,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
        ],
      },
      {
        id: 2,
        code: 222222,
        name: '木木1',
        describe: '描述2',
        creatorName: '大大创建2',
        creatorTime: '2019/10/20',
        changerName: '大大修改2',
        changerTime: '2019/10/20',
        status: 2,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目2',
        copyRight: '1.2',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
      },
      {
        id: 3,
        code: 111111,
        name: '木木1',
        describe: '描述1',
        creatorName: '大大创建1',
        creatorTime: '2019/10/20',
        changerName: '大大修改1',
        changerTime: '2019/10/20',
        status: 3,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目1',
        copyRight: '1.1',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
        list: [
          {
            id: 3,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 1,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
          {
            id: 4,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 2,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
        ],
      },
      {
        id: 4,
        code: 222222,
        name: '木木1',
        describe: '描述2',
        creatorName: '大大创建2',
        creatorTime: '2019/10/20',
        changerName: '大大修改2',
        changerTime: '2019/10/20',
        status: 4,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目2',
        copyRight: '1.2',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
      },
      {
        id: 5,
        code: 111111,
        name: '木木1',
        describe: '描述1',
        creatorName: '大大创建1',
        creatorTime: '2019/10/20',
        changerName: '大大修改1',
        changerTime: '2019/10/20',
        status: 5,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目1',
        copyRight: '1.1',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
        list: [
          {
            id: 3,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 1,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
          {
            id: 4,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 2,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
        ],
      },
      {
        id: 6,
        code: 222222,
        name: '木木1',
        describe: '描述2',
        creatorName: '大大创建2',
        creatorTime: '2019/10/20',
        changerName: '大大修改2',
        changerTime: '2019/10/20',
        status: 3,
        label: ['yellowgreen', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目2',
        copyRight: '1.2',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
      },
    ],
  },
  effects: {},
  reducers: {},
};
export default projectModel;
