const projectModel = {
  namespace: 'projectManage',
  state: {
    projectManage: [
      {
        id: 1,
        code: 111111,
        name: '木木1',
        describe: '描述1',
        creatorName: '大大创建1',
        creatorTime: '2019/10/20',
        changerName: '大大修改1',
        changerTime: '2019/10/20',
        status: 1,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目1',
        copyRight: '1.1',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
        list: [
          {
            id: 3,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 1,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
          {
            id: 4,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 2,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
        ],
      },
      {
        id: 2,
        code: 222222,
        name: '木木1',
        describe: '描述2',
        creatorName: '大大创建2',
        creatorTime: '2019/10/20',
        changerName: '大大修改2',
        changerTime: '2019/10/20',
        status: 2,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目2',
        copyRight: '1.2',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
      },
      {
        id: 3,
        code: 111111,
        name: '木木1',
        describe: '描述1',
        creatorName: '大大创建1',
        creatorTime: '2019/10/20',
        changerName: '大大修改1',
        changerTime: '2019/10/20',
        status: 3,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目1',
        copyRight: '1.1',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
        list: [
          {
            id: 3,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 1,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
          {
            id: 4,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 2,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
        ],
      },
      {
        id: 4,
        code: 222222,
        name: '木木1',
        describe: '描述2',
        creatorName: '大大创建2',
        creatorTime: '2019/10/20',
        changerName: '大大修改2',
        changerTime: '2019/10/20',
        status: 4,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目2',
        copyRight: '1.2',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
      },
      {
        id: 5,
        code: 111111,
        name: '木木1',
        describe: '描述1',
        creatorName: '大大创建1',
        creatorTime: '2019/10/20',
        changerName: '大大修改1',
        changerTime: '2019/10/20',
        status: 5,
        label: ['pink', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目1',
        copyRight: '1.1',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
        list: [
          {
            id: 3,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 1,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
          {
            id: 4,
            code: 12,
            name: '木木12',
            describe: '描述12',
            creatorName: '大大创建12',
            creatorTime: '2019/10/20',
            changerName: '大大修改2',
            changerTime: '2019/10/20',
            status: 2,
            memberNumber: 10,
            projectModelName: '**项目12',
            copyRight: '1.2',
            StartTime: '2019/1/1',
            endTime: '2019/10/1',
          },
        ],
      },
      {
        id: 6,
        code: 222222,
        name: '木木1',
        describe: '描述2',
        creatorName: '大大创建2',
        creatorTime: '2019/10/20',
        changerName: '大大修改2',
        changerTime: '2019/10/20',
        status: 3,
        label: ['yellowgreen', 'purple', 'blue', 'green'],
        memberNumber: 10,
        projectModelName: '**项目2',
        copyRight: '1.2',
        StartTime: '2019/1/1',
        endTime: '2019/10/1',
      },
    ],
    statusList: [
      { value: 1, text: '未开始', status: 'default' },
      { value: 2, text: '进行中', status: 'Warning' },
      { value: 3, text: '已完成', status: 'success' },
      { value: 4, text: '已终止', status: 'error' },
      { value: 5, text: '待处理', status: 'Processing' },
    ],
    // 业务伙伴认证状态
    BpCertificationStatus: [
      {
        id: 1,
        name: '未认证',
        // i18n: 'bp.unapproved',
        badge: 'default',
      },
      {
        id: 2,
        name: '审核中',
        // i18n: 'bp.processing',
        badge: 'warning',
      },
      {
        id: 3,
        name: '部分认证',
        // i18n: 'bp.partialApproved',
        badge: 'warning',
      },
      {
        id: 4,
        name: '已认证',
        // i18n: 'bp.approveds',
        badge: 'success',
      },
    ],
    // 销售范围冻结状态
    SalesOrderBlock: [
      {
        id: 1,
        name: '冻结',
        // i18n: 'bp.block',
        badge: 'error',
      },
      {
        id: 2,
        name: '正常',
        // i18n: 'bp.normal',
        badge: 'success',
      },
    ],
    // 标签
    labelList: [
      {
        id: 1,
        name: '真核转录组',
        text: 'eukaryotic_transcriptome',
      },
      {
        id: 2,
        name: '宏转录组',
        text: 'metatranscriptome',
      },
      {
        id: 3,
        name: '真菌基因组',
        text: 'fugus_genome',
      },
      {
        id: 4,
        name: '外显子组',
        text: 'exome',
      },
      {
        id: 5,
        name: '简化基因组',
        text: 'RAD',
      },
      {
        id: 6,
        name: '宏基因组',
        text: 'metagenome',
      },
      {
        id: 7,
        name: '微生物基因组',
        text: 'microbial_genome',
      },
      {
        id: 8,
        name: '重测序',
        text: 'resequencing',
      },
      {
        id: 9,
        name: '原核转录组',
        text: 'prokaryotic_transcriptom',
      },
      {
        id: 10,
        name: '小RNA',
        text: 'microRNA',
      },
      {
        id: 11,
        name: '动植物基因组',
        text: 'eukaryotic_genome',
      },
      {
        id: 12,
        name: '微生物多样性',
        text: 'microbial_diversity',
      },
      {
        id: 13,
        name: '表观遗传学',
        text: 'epigenetics',
      },
    ],
    // 点击查看的数据
    viewlist: [],
    // 修改项目参数
    projectData:[],
  },
  effects: {},
  reducers: {
    setviewlist(state, payload) {
      // console.log(action);
      return { ...state, viewlist: payload };
    },

    setProjectData(state, action) {
      return { ...state, projectData: action.payload };
    }
  },
};
export default projectModel;
